//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace denemestaj.AltinkaynakWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://data.altinkaynak.com/", ConfigurationName="AltinkaynakWebService.DataServiceSoap")]
    public interface DataServiceSoap {
        
        // CODEGEN: Generating message contract since message GetCurrencyRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://data.altinkaynak.com/GetCurrency", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        denemestaj.AltinkaynakWebService.GetCurrencyResponse GetCurrency(denemestaj.AltinkaynakWebService.GetCurrencyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://data.altinkaynak.com/GetCurrency", ReplyAction="*")]
        System.Threading.Tasks.Task<denemestaj.AltinkaynakWebService.GetCurrencyResponse> GetCurrencyAsync(denemestaj.AltinkaynakWebService.GetCurrencyRequest request);
        
        // CODEGEN: Generating message contract since message GetGoldRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://data.altinkaynak.com/GetGold", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        denemestaj.AltinkaynakWebService.GetGoldResponse GetGold(denemestaj.AltinkaynakWebService.GetGoldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://data.altinkaynak.com/GetGold", ReplyAction="*")]
        System.Threading.Tasks.Task<denemestaj.AltinkaynakWebService.GetGoldResponse> GetGoldAsync(denemestaj.AltinkaynakWebService.GetGoldRequest request);
        
        // CODEGEN: Generating message contract since message GetMainRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://data.altinkaynak.com/GetMain", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        denemestaj.AltinkaynakWebService.GetMainResponse GetMain(denemestaj.AltinkaynakWebService.GetMainRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://data.altinkaynak.com/GetMain", ReplyAction="*")]
        System.Threading.Tasks.Task<denemestaj.AltinkaynakWebService.GetMainResponse> GetMainAsync(denemestaj.AltinkaynakWebService.GetMainRequest request);
        
        // CODEGEN: Generating message contract since message GetParityRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://data.altinkaynak.com/GetParity", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        denemestaj.AltinkaynakWebService.GetParityResponse GetParity(denemestaj.AltinkaynakWebService.GetParityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://data.altinkaynak.com/GetParity", ReplyAction="*")]
        System.Threading.Tasks.Task<denemestaj.AltinkaynakWebService.GetParityResponse> GetParityAsync(denemestaj.AltinkaynakWebService.GetParityRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.altinkaynak.com/")]
    public partial class AuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCurrency", WrapperNamespace="http://data.altinkaynak.com/", IsWrapped=true)]
    public partial class GetCurrencyRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://data.altinkaynak.com/")]
        public denemestaj.AltinkaynakWebService.AuthHeader AuthHeader;
        
        public GetCurrencyRequest() {
        }
        
        public GetCurrencyRequest(denemestaj.AltinkaynakWebService.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCurrencyResponse", WrapperNamespace="http://data.altinkaynak.com/", IsWrapped=true)]
    public partial class GetCurrencyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://data.altinkaynak.com/", Order=0)]
        public string GetCurrencyResult;
        
        public GetCurrencyResponse() {
        }
        
        public GetCurrencyResponse(string GetCurrencyResult) {
            this.GetCurrencyResult = GetCurrencyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGold", WrapperNamespace="http://data.altinkaynak.com/", IsWrapped=true)]
    public partial class GetGoldRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://data.altinkaynak.com/")]
        public denemestaj.AltinkaynakWebService.AuthHeader AuthHeader;
        
        public GetGoldRequest() {
        }
        
        public GetGoldRequest(denemestaj.AltinkaynakWebService.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGoldResponse", WrapperNamespace="http://data.altinkaynak.com/", IsWrapped=true)]
    public partial class GetGoldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://data.altinkaynak.com/", Order=0)]
        public string GetGoldResult;
        
        public GetGoldResponse() {
        }
        
        public GetGoldResponse(string GetGoldResult) {
            this.GetGoldResult = GetGoldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMain", WrapperNamespace="http://data.altinkaynak.com/", IsWrapped=true)]
    public partial class GetMainRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://data.altinkaynak.com/")]
        public denemestaj.AltinkaynakWebService.AuthHeader AuthHeader;
        
        public GetMainRequest() {
        }
        
        public GetMainRequest(denemestaj.AltinkaynakWebService.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMainResponse", WrapperNamespace="http://data.altinkaynak.com/", IsWrapped=true)]
    public partial class GetMainResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://data.altinkaynak.com/", Order=0)]
        public string GetMainResult;
        
        public GetMainResponse() {
        }
        
        public GetMainResponse(string GetMainResult) {
            this.GetMainResult = GetMainResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetParity", WrapperNamespace="http://data.altinkaynak.com/", IsWrapped=true)]
    public partial class GetParityRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://data.altinkaynak.com/")]
        public denemestaj.AltinkaynakWebService.AuthHeader AuthHeader;
        
        public GetParityRequest() {
        }
        
        public GetParityRequest(denemestaj.AltinkaynakWebService.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetParityResponse", WrapperNamespace="http://data.altinkaynak.com/", IsWrapped=true)]
    public partial class GetParityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://data.altinkaynak.com/", Order=0)]
        public string GetParityResult;
        
        public GetParityResponse() {
        }
        
        public GetParityResponse(string GetParityResult) {
            this.GetParityResult = GetParityResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DataServiceSoapChannel : denemestaj.AltinkaynakWebService.DataServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServiceSoapClient : System.ServiceModel.ClientBase<denemestaj.AltinkaynakWebService.DataServiceSoap>, denemestaj.AltinkaynakWebService.DataServiceSoap {
        
        public DataServiceSoapClient() {
        }
        
        public DataServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        denemestaj.AltinkaynakWebService.GetCurrencyResponse denemestaj.AltinkaynakWebService.DataServiceSoap.GetCurrency(denemestaj.AltinkaynakWebService.GetCurrencyRequest request) {
            return base.Channel.GetCurrency(request);
        }
        
        public string GetCurrency(denemestaj.AltinkaynakWebService.AuthHeader AuthHeader) {
            denemestaj.AltinkaynakWebService.GetCurrencyRequest inValue = new denemestaj.AltinkaynakWebService.GetCurrencyRequest();
            inValue.AuthHeader = AuthHeader;
            denemestaj.AltinkaynakWebService.GetCurrencyResponse retVal = ((denemestaj.AltinkaynakWebService.DataServiceSoap)(this)).GetCurrency(inValue);
            return retVal.GetCurrencyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<denemestaj.AltinkaynakWebService.GetCurrencyResponse> denemestaj.AltinkaynakWebService.DataServiceSoap.GetCurrencyAsync(denemestaj.AltinkaynakWebService.GetCurrencyRequest request) {
            return base.Channel.GetCurrencyAsync(request);
        }
        
        public System.Threading.Tasks.Task<denemestaj.AltinkaynakWebService.GetCurrencyResponse> GetCurrencyAsync(denemestaj.AltinkaynakWebService.AuthHeader AuthHeader) {
            denemestaj.AltinkaynakWebService.GetCurrencyRequest inValue = new denemestaj.AltinkaynakWebService.GetCurrencyRequest();
            inValue.AuthHeader = AuthHeader;
            return ((denemestaj.AltinkaynakWebService.DataServiceSoap)(this)).GetCurrencyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        denemestaj.AltinkaynakWebService.GetGoldResponse denemestaj.AltinkaynakWebService.DataServiceSoap.GetGold(denemestaj.AltinkaynakWebService.GetGoldRequest request) {
            return base.Channel.GetGold(request);
        }
        
        public string GetGold(denemestaj.AltinkaynakWebService.AuthHeader AuthHeader) {
            denemestaj.AltinkaynakWebService.GetGoldRequest inValue = new denemestaj.AltinkaynakWebService.GetGoldRequest();
            inValue.AuthHeader = AuthHeader;
            denemestaj.AltinkaynakWebService.GetGoldResponse retVal = ((denemestaj.AltinkaynakWebService.DataServiceSoap)(this)).GetGold(inValue);
            return retVal.GetGoldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<denemestaj.AltinkaynakWebService.GetGoldResponse> denemestaj.AltinkaynakWebService.DataServiceSoap.GetGoldAsync(denemestaj.AltinkaynakWebService.GetGoldRequest request) {
            return base.Channel.GetGoldAsync(request);
        }
        
        public System.Threading.Tasks.Task<denemestaj.AltinkaynakWebService.GetGoldResponse> GetGoldAsync(denemestaj.AltinkaynakWebService.AuthHeader AuthHeader) {
            denemestaj.AltinkaynakWebService.GetGoldRequest inValue = new denemestaj.AltinkaynakWebService.GetGoldRequest();
            inValue.AuthHeader = AuthHeader;
            return ((denemestaj.AltinkaynakWebService.DataServiceSoap)(this)).GetGoldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        denemestaj.AltinkaynakWebService.GetMainResponse denemestaj.AltinkaynakWebService.DataServiceSoap.GetMain(denemestaj.AltinkaynakWebService.GetMainRequest request) {
            return base.Channel.GetMain(request);
        }
        
        public string GetMain(denemestaj.AltinkaynakWebService.AuthHeader AuthHeader) {
            denemestaj.AltinkaynakWebService.GetMainRequest inValue = new denemestaj.AltinkaynakWebService.GetMainRequest();
            inValue.AuthHeader = AuthHeader;
            denemestaj.AltinkaynakWebService.GetMainResponse retVal = ((denemestaj.AltinkaynakWebService.DataServiceSoap)(this)).GetMain(inValue);
            return retVal.GetMainResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<denemestaj.AltinkaynakWebService.GetMainResponse> denemestaj.AltinkaynakWebService.DataServiceSoap.GetMainAsync(denemestaj.AltinkaynakWebService.GetMainRequest request) {
            return base.Channel.GetMainAsync(request);
        }
        
        public System.Threading.Tasks.Task<denemestaj.AltinkaynakWebService.GetMainResponse> GetMainAsync(denemestaj.AltinkaynakWebService.AuthHeader AuthHeader) {
            denemestaj.AltinkaynakWebService.GetMainRequest inValue = new denemestaj.AltinkaynakWebService.GetMainRequest();
            inValue.AuthHeader = AuthHeader;
            return ((denemestaj.AltinkaynakWebService.DataServiceSoap)(this)).GetMainAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        denemestaj.AltinkaynakWebService.GetParityResponse denemestaj.AltinkaynakWebService.DataServiceSoap.GetParity(denemestaj.AltinkaynakWebService.GetParityRequest request) {
            return base.Channel.GetParity(request);
        }
        
        public string GetParity(denemestaj.AltinkaynakWebService.AuthHeader AuthHeader) {
            denemestaj.AltinkaynakWebService.GetParityRequest inValue = new denemestaj.AltinkaynakWebService.GetParityRequest();
            inValue.AuthHeader = AuthHeader;
            denemestaj.AltinkaynakWebService.GetParityResponse retVal = ((denemestaj.AltinkaynakWebService.DataServiceSoap)(this)).GetParity(inValue);
            return retVal.GetParityResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<denemestaj.AltinkaynakWebService.GetParityResponse> denemestaj.AltinkaynakWebService.DataServiceSoap.GetParityAsync(denemestaj.AltinkaynakWebService.GetParityRequest request) {
            return base.Channel.GetParityAsync(request);
        }
        
        public System.Threading.Tasks.Task<denemestaj.AltinkaynakWebService.GetParityResponse> GetParityAsync(denemestaj.AltinkaynakWebService.AuthHeader AuthHeader) {
            denemestaj.AltinkaynakWebService.GetParityRequest inValue = new denemestaj.AltinkaynakWebService.GetParityRequest();
            inValue.AuthHeader = AuthHeader;
            return ((denemestaj.AltinkaynakWebService.DataServiceSoap)(this)).GetParityAsync(inValue);
        }
    }
}
